module Kindle
  class Markdown
    def self.save(book, path)
      filename = path + "/" + book.to_file_name + ".md"

      ::File.open(filename, 'w') do |file|
        file.puts("# #{book.title}\n\n")
        file.puts("Author: #{book.author}")
        file.puts("Last updated: #{book.last_updated}")
        file.puts("Generated by: kindle.rb")

        file.puts("\n# Notes\n\n")
        book.notes.each do |note|
          file.puts(note.content.to_s + "\n\n")
        end
      end

    end
  end
end
